export const ActionTypes = {
  SET_POSTS: "SET_POSTS",
  SELECTED_POST: "SELECTED_POST",
  REMOVE_SELECTED_POST: "REMOVE_SELECTED_POST",
  SET_COMMENTS: "SET_COMMENTS",
  FAVOURITE_ADDED: "FAVOURITE_ADDED",
  FAVOURITE_REMOVED: "FAVOURITE_REMOVED",
};
